/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author manl_
 */
public class ViewBlocNotas extends javax.swing.JFrame {

    /**
     * Creates new form ViewBlocNotas
     */
    public ViewBlocNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChosser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_texto = new javax.swing.JTextArea();
        jp_cifrado = new javax.swing.JPanel();
        jl_cifrado = new javax.swing.JLabel();
        jtf_cifrado = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_menu = new javax.swing.JMenu();
        jMI_abrir = new javax.swing.JMenuItem();
        jMI_guardar = new javax.swing.JMenuItem();
        jMI_cifrar = new javax.swing.JMenuItem();
        jMI_descifrar = new javax.swing.JMenuItem();

        jFileChosser.setApproveButtonText("");
        jFileChosser.setBackground(new java.awt.Color(255, 0, 0));
        jFileChosser.setCurrentDirectory(new java.io.File("C:\\archivos"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta_texto.setColumns(20);
        jta_texto.setRows(5);
        jScrollPane1.setViewportView(jta_texto);

        jp_cifrado.setBackground(new java.awt.Color(0, 255, 102));

        jl_cifrado.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        jl_cifrado.setText("Ingrese valor del cifrado:");

        jtf_cifrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_cifrado.setText("0");

        javax.swing.GroupLayout jp_cifradoLayout = new javax.swing.GroupLayout(jp_cifrado);
        jp_cifrado.setLayout(jp_cifradoLayout);
        jp_cifradoLayout.setHorizontalGroup(
            jp_cifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cifradoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jl_cifrado)
                .addGap(52, 52, 52)
                .addComponent(jtf_cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_cifradoLayout.setVerticalGroup(
            jp_cifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cifradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_cifradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cifrado)
                    .addComponent(jtf_cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(0, 204, 204));

        jM_menu.setBackground(new java.awt.Color(51, 255, 255));
        jM_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jM_menu.setText("Menú");

        jMI_abrir.setText("Abrir");
        jM_menu.add(jMI_abrir);

        jMI_guardar.setText("Guardar");
        jM_menu.add(jMI_guardar);

        jMI_cifrar.setText("Cifrar");
        jM_menu.add(jMI_cifrar);

        jMI_descifrar.setText("Descifrar");
        jM_menu.add(jMI_descifrar);

        jMenuBar1.add(jM_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jp_cifrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jp_cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBlocNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChosser;
    public javax.swing.JMenuItem jMI_abrir;
    public javax.swing.JMenuItem jMI_cifrar;
    public javax.swing.JMenuItem jMI_descifrar;
    public javax.swing.JMenuItem jMI_guardar;
    public javax.swing.JMenu jM_menu;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jl_cifrado;
    public javax.swing.JPanel jp_cifrado;
    public javax.swing.JTextArea jta_texto;
    public javax.swing.JTextField jtf_cifrado;
    // End of variables declaration//GEN-END:variables
}
